-- Auto-generated by build_message_lists.py
-- DO NOT EDIT MANUALLY

local mod = {}

-- Set of valid message list names for O(1) lookup
mod.MESSAGE_LISTS = {
   ["blueprint-book-help"] = true,
   ["category-rows-help"] = true,
   ["ch1"] = true,
   ["ch10"] = true,
   ["ch11"] = true,
   ["ch12"] = true,
   ["ch13"] = true,
   ["ch14"] = true,
   ["ch15"] = true,
   ["ch2"] = true,
   ["ch3"] = true,
   ["ch4"] = true,
   ["ch5"] = true,
   ["ch6"] = true,
   ["ch7"] = true,
   ["ch8"] = true,
   ["ch9"] = true,
   ["crafting-menu-help"] = true,
   ["crafting-queue-help"] = true,
   ["debug-menu-help"] = true,
   ["decider-combinator"] = true,
   ["equipment-grid-help"] = true,
   ["general-ui-help"] = true,
   ["inventory-grid-help"] = true,
   ["map-help"] = true,
   ["menu-help"] = true,
   ["spidertron-remote-protohelp"] = true,
   ["trains-overview-help"] = true,
   ["warnings-menu-help"] = true,
}

mod.MESSAGE_LISTS_HASH = "064a6ea8fd48c51e2998d6148fb4742e04a8a6e0ef9487b0195e198953a854a5"

return mod
